### PR TITLE
CI: Ensures correct python build versions

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
Fixes CI to build with the declared Python version. Ensures #126 does not happen again.

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
@jcmgray Can you double check the [Py35](https://github.com/dgasmith/opt_einsum/pull/128/commits/3a083bdd3ac9d3dcf21857e8246ba0a0e433cbbf) edits?

**Comment by dgasmith** [comment]
Yes, without OrderedDict `dp` gives non-deterministic results.

A small test shows initialization time is about 3x larger, but averages to microseconds for our use case. Lookup time is equivalent and iteration time is about 1.3x larger. Average over several tests show the `dp` takes a 2-4% performance hit. Not the best, but keeps things simple.

**Comment by jcmgray** [comment]
Cool, thanks for the numbers! I agree that seems reasonable.

**Comment by dgasmith** [comment]
Great! I will go ahead with a release in this case.

**Pull request merged**
